name: slack

on:
  push:
    branches:
      - main
    paths:
      - "pages/standards/**"

  workflow_dispatch:
    inputs:
      release-sha:
        description: SHA of a production release
        required: true
jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files: "pages/standards/**"

      - name: Generate Slack message body
        id: slack-message-body
        run: |
          source ./scripts/slack-notification-utils.sh

          json=$(get_slack_message_json \
            "$(get_section_json "New Guidelines" ${{ steps.changed-files.outputs.added_files }})" \
            "$(get_section_json "Updated Guidelines" ${{ steps.changed-files.outputs.modified_files }})" \
            "$(get_section_json "Deleted Guidelines" ${{ steps.changed-files.outputs.deleted_files }})"
          )

          echo "result=$json" >> $GITHUB_OUTPUT

      - name: Create full Slack message
        run: |
          echo "
            {
              \"blocks\": [
                {
                  \"type\": \"header\",
                  \"text\": {
                    \"type\": \"plain_text\",
                    \"text\": \":rocket: Web Coding Guidelines - Deployed\",
                    \"emoji\": true
                  }
                },
                {
                  \"type\": \"section\",
                  \"text\": {
                    \"type\": \"mrkdwn\",
                    \"text\": \"_A new version of Web Coding Guidelines by *${{ github.event.head_commit.author.name }}* has been deployed._\"
                  }
                },
                {
                  \"type\": \"divider\"
                }
                ${{ steps.slack-message-body.outputs.result }}
              ]
            }
          "
